engines:
 duplication:
  enabled: true
  config:
    languages:
      ruby:
        mass_threshold: 25
 rubocop:
  enabled: true
 scss-lint:
  enabled: true

ratings:
 paths:
 - "**.rb"
 - "**.scss"

exclude_paths:
